import {
  VERIFICATION_COMMAND_RULE_SET_VERSION,
  VERIFICATION_EVIDENCE_SCHEMA_VERSION,
  VERIFICATION_EXTRACTOR_VERSION,
  VERIFICATION_MAX_ARTIFACT_BYTES,
  VERIFICATION_MAX_COMMAND_OBSERVATIONS,
  VERIFICATION_MAX_RUN_EVENTS,
  VERIFICATION_MAX_TEST_FILE_REFERENCES,
  VERIFICATION_OUTPUT_REDUCTION_POLICY_VERSION,
} from "@ownloop/contracts";

export const DETERMINISTIC_VERIFICATION_EVIDENCE_ROLE =
  "deterministic-verification-evidence-v1" as const;
export const DETERMINISTIC_VERIFICATION_EVIDENCE_KIND =
  "deterministic-verification-evidence-v1" as const;
export const DETERMINISTIC_VERIFICATION_EVIDENCE_MEDIA_TYPE =
  "application/vnd.ownloop.verification-evidence+json" as const;
export const DETERMINISTIC_VERIFICATION_EVIDENCE_SENSITIVITY = "sensitive" as const;
export const VERIFICATION_EXTRACTION_EVENT_DEDUPLICATION_VERSION =
  "v1:verification-extraction" as const;
export const MAX_VERIFICATION_EXTRACTION_BATCH = 25;
export const MAX_ACCEPTED_COMMAND_CODE_POINTS = 16_384;
export const MAX_OUTPUT_EXCERPT_LINES = 64;
export const MAX_OUTPUT_EXCERPT_UTF8_BYTES = 16 * 1024;

export {
  VERIFICATION_COMMAND_RULE_SET_VERSION,
  VERIFICATION_EVIDENCE_SCHEMA_VERSION,
  VERIFICATION_EXTRACTOR_VERSION,
  VERIFICATION_MAX_ARTIFACT_BYTES,
  VERIFICATION_MAX_COMMAND_OBSERVATIONS,
  VERIFICATION_MAX_RUN_EVENTS,
  VERIFICATION_MAX_TEST_FILE_REFERENCES,
  VERIFICATION_OUTPUT_REDUCTION_POLICY_VERSION,
};
