import {
  CHANGE_CLASSIFICATION_MAX_ARTIFACT_BYTES,
  CHANGE_CLASSIFICATION_MAX_ENTRIES,
  CHANGE_CLASSIFICATION_RULE_SET_VERSION,
  CHANGE_CLASSIFICATION_TAXONOMY_VERSION,
  CHANGE_CLASSIFIER_VERSION,
} from "@ownloop/contracts";

export const DETERMINISTIC_CHANGE_CLASSIFICATION_ROLE =
  "deterministic-change-classification-v1" as const;
export const DETERMINISTIC_CHANGE_CLASSIFICATION_KIND =
  "deterministic-change-classification-v1" as const;
export const DETERMINISTIC_CHANGE_CLASSIFICATION_MEDIA_TYPE =
  "application/vnd.ownloop.change-classification+json" as const;
export const DETERMINISTIC_CHANGE_CLASSIFICATION_SENSITIVITY = "sensitive" as const;
export const MAX_CHANGE_CLASSIFICATION_BATCH = 25;

export {
  CHANGE_CLASSIFICATION_MAX_ARTIFACT_BYTES,
  CHANGE_CLASSIFICATION_MAX_ENTRIES,
  CHANGE_CLASSIFICATION_RULE_SET_VERSION,
  CHANGE_CLASSIFICATION_TAXONOMY_VERSION,
  CHANGE_CLASSIFIER_VERSION,
};
