import {
  CANDIDATE_GENERATION_DEFAULT_MAX_ATTEMPTS,
  CANDIDATE_GENERATION_MAX_BATCH_RUNS,
  CANDIDATE_GENERATION_MAX_PRODUCT_CANDIDATES,
  CANDIDATE_GENERATION_MAX_REQUEST_BYTES,
  CANDIDATE_GENERATION_MAX_RESPONSE_BYTES,
  CANDIDATE_GENERATION_PROMPT_TEMPLATE_VERSION,
  CANDIDATE_GENERATION_RESPONSE_SCHEMA_VERSION,
  CANDIDATE_GENERATOR_VERSION,
} from "@ownloop/contracts";

export const CANDIDATE_GENERATION_ARTIFACT_KIND = "candidate-moment-batch-v1" as const;
export const CANDIDATE_GENERATION_ARTIFACT_MEDIA_TYPE =
  "application/vnd.ownloop.candidate-moment-batch+json" as const;
export const CANDIDATE_GENERATION_ARTIFACT_SENSITIVITY = "sensitive" as const;
export const CANDIDATE_GENERATION_ARTIFACT_ROLE_PREFIX = "candidate-moment-batch-v1" as const;
export const CANDIDATE_GENERATION_RESPONSE_FORMAT_NAME =
  "ownloop_candidate_moment_batch_v1" as const;
export const CANDIDATE_GENERATION_ENDPOINT_PATH = "/v1/responses" as const;

export {
  CANDIDATE_GENERATION_DEFAULT_MAX_ATTEMPTS,
  CANDIDATE_GENERATION_MAX_BATCH_RUNS,
  CANDIDATE_GENERATION_MAX_PRODUCT_CANDIDATES,
  CANDIDATE_GENERATION_MAX_REQUEST_BYTES,
  CANDIDATE_GENERATION_MAX_RESPONSE_BYTES,
  CANDIDATE_GENERATION_PROMPT_TEMPLATE_VERSION,
  CANDIDATE_GENERATION_RESPONSE_SCHEMA_VERSION,
  CANDIDATE_GENERATOR_VERSION,
};
