export const APP_NAME = "OwnLoop";
export const BOOTSTRAP_LABEL = "v0.1 bootstrap";

export function formatBootstrapName(name: string): string {
  return `${name} ${BOOTSTRAP_LABEL}`;
}

export type {
  ClaudeEffort,
  ClaudeHookCommonFields,
  ClaudeLooseSourceObject,
  SupportedClaudeHookName,
} from "./claude-hook-common.js";
export {
  ClaudeEffortSchema,
  ClaudeHookCommonFieldsSchema,
  ClaudeLooseSourceObjectSchema,
  SUPPORTED_CLAUDE_HOOK_NAMES,
  SupportedClaudeHookNameSchema,
} from "./claude-hook-common.js";
export type {
  ClaudeKnownSessionEndReason,
  ClaudeKnownSessionStartSource,
  ClaudeKnownStopFailureError,
  ClaudePostToolBatchCall,
  ClaudePostToolBatchPayload,
  ClaudePostToolUseFailurePayload,
  ClaudePostToolUsePayload,
  ClaudePreToolUsePayload,
  ClaudeSessionEndPayload,
  ClaudeSessionStartPayload,
  ClaudeStopFailurePayload,
  ClaudeStopPayload,
  ClaudeUserPromptSubmitPayload,
  SupportedClaudeHookPayload,
} from "./claude-hook-payloads.js";
export {
  CLAUDE_SESSION_END_REASONS,
  CLAUDE_SESSION_START_SOURCES,
  CLAUDE_STOP_FAILURE_ERRORS,
  ClaudeKnownSessionEndReasonSchema,
  ClaudeKnownSessionStartSourceSchema,
  ClaudeKnownStopFailureErrorSchema,
  ClaudePostToolBatchCallSchema,
  ClaudePostToolBatchPayloadSchema,
  ClaudePostToolUseFailurePayloadSchema,
  ClaudePostToolUsePayloadSchema,
  ClaudePreToolUsePayloadSchema,
  ClaudeSessionEndPayloadSchema,
  ClaudeSessionStartPayloadSchema,
  ClaudeStopFailurePayloadSchema,
  ClaudeStopPayloadSchema,
  ClaudeUserPromptSubmitPayloadSchema,
  SupportedClaudeHookPayloadSchema,
} from "./claude-hook-payloads.js";
export type {
  IngestionAcceptedResponse,
  IngestionErrorCode,
  IngestionRejectedResponse,
  IngestionResponse,
  ValidationIssuePathSegment,
  ValidationIssueSummary,
} from "./ingestion-response.js";
export {
  INGESTION_ERROR_CODES,
  IngestionAcceptedResponseSchema,
  IngestionErrorCodeSchema,
  IngestionRejectedResponseSchema,
  IngestionResponseSchema,
  ValidationIssuePathSegmentSchema,
  ValidationIssueSummarySchema,
} from "./ingestion-response.js";
export type {
  HmacSha256Fingerprint,
  IngressDeduplicationKey,
  IngressRedactionRuleId,
  IngressSecurityErrorCode,
  IngressSecurityErrorDetails,
  PreparedIngressReceiptV1,
  RedactionSummaryV1,
} from "./ingress-security.js";
export {
  HmacSha256FingerprintSchema,
  INGRESS_CANONICALIZATION_VERSION,
  INGRESS_REDACTION_POLICY_VERSION,
  INGRESS_REDACTION_RULE_IDS,
  INGRESS_SECURITY_ERROR_CODES,
  IngressDeduplicationKeySchema,
  IngressRedactionRuleIdSchema,
  IngressSecurityErrorCodeSchema,
  IngressSecurityErrorDetailsSchema,
  IngressSecurityPathSegmentSchema,
  PreparedIngressReceiptV1Schema,
  RedactionSummaryV1Schema,
} from "./ingress-security.js";
export type { ClaudeAdapterIngress } from "./ingress-wrapper.js";
export {
  CLAUDE_INGRESS_CONTRACT_VERSION,
  ClaudeAdapterIngressSchema,
} from "./ingress-wrapper.js";
export type {
  FinalDiffManifestV1,
  RawRunReplayV1,
  ReplayArtifactReferenceV1,
  ReplayCausalLinkV1,
  ReplayChangedFileV1,
  ReplayCompleteness,
  ReplayErrorCode,
  ReplayErrorResponse,
  ReplayEvidenceGapV1,
  ReplayFinalizationV1,
  ReplayGitBaselineV1,
  ReplayPresence,
  ReplayReconciliationV1,
  ReplayRunListResponseV1,
  ReplayRunStatus,
  ReplayRunSummaryV1,
  ReplayTimelineEventV1,
  ReplayTimelinePayloadV1,
  ReplayVerificationV1,
} from "./replay.js";
export {
  FinalDiffManifestV1Schema,
  RAW_REPLAY_SCHEMA_VERSION,
  RawRunReplayV1Schema,
  REPLAY_CAUSAL_LINK_TYPES,
  REPLAY_CAUSAL_NODE_KINDS,
  REPLAY_COMPLETENESS_STATES,
  REPLAY_DEFAULT_LIST_LIMIT,
  REPLAY_ERROR_CODES,
  REPLAY_MAX_ARTIFACT_BYTES,
  REPLAY_MAX_LIST_LIMIT,
  REPLAY_PROMPT_PREVIEW_CODE_POINTS,
  REPLAY_RUN_STATUSES,
  REPLAY_TIMELINE_DETAIL_CODE_POINTS,
  ReplayArtifactReferenceV1Schema,
  ReplayCausalLinkTypeSchema,
  ReplayCausalLinkV1Schema,
  ReplayCausalNodeKindSchema,
  ReplayChangedFileV1Schema,
  ReplayCompletenessSchema,
  ReplayErrorCodeSchema,
  ReplayErrorResponseSchema,
  ReplayEvidenceGapV1Schema,
  ReplayFinalizationV1Schema,
  ReplayGitBaselineV1Schema,
  ReplayPresenceSchema,
  ReplayReconciliationV1Schema,
  ReplayRunListResponseV1Schema,
  ReplayRunStatusSchema,
  ReplayRunSummaryV1Schema,
  ReplayTimelineEventV1Schema,
  ReplayTimelineMetadataV1Schema,
  ReplayTimelinePayloadV1Schema,
  ReplayVerificationV1Schema,
} from "./replay.js";

export type {
  DeterministicEvidenceGraphV1,
  EvidenceEdgeId,
  EvidenceEdgeType,
  EvidenceEdgeV1,
  EvidenceGraphDiagnosticCode,
  EvidenceGraphKindCountV1,
  EvidenceGraphLimitation,
  EvidenceGraphOutcome,
  EvidenceId,
  EvidenceNodeKind,
  EvidenceNodeLocatorV1,
  EvidenceNodeMetadataV1,
  EvidenceNodeV1,
  EvidenceResolutionAnchorKind,
  EvidenceResolutionV1,
} from "./evidence-graph.js";
export {
  DeterministicEvidenceGraphV1Schema,
  EVIDENCE_EDGE_TYPES,
  EVIDENCE_GRAPH_BUILDER_VERSION,
  EVIDENCE_GRAPH_DIAGNOSTIC_CODES,
  EVIDENCE_GRAPH_LIMITATIONS,
  EVIDENCE_GRAPH_MAX_ARTIFACT_BYTES,
  EVIDENCE_GRAPH_MAX_EDGES,
  EVIDENCE_GRAPH_MAX_NODES,
  EVIDENCE_GRAPH_OUTCOMES,
  EVIDENCE_GRAPH_SCHEMA_VERSION,
  EVIDENCE_GRAPH_TAXONOMY_VERSION,
  EVIDENCE_NODE_KINDS,
  EVIDENCE_RESOLUTION_ANCHOR_KINDS,
  EvidenceEdgeIdSchema,
  EvidenceEdgeTypeSchema,
  EvidenceEdgeV1Schema,
  EvidenceGraphDiagnosticCodeSchema,
  EvidenceGraphKindCountV1Schema,
  EvidenceGraphLimitationSchema,
  EvidenceGraphOutcomeSchema,
  EvidenceIdSchema,
  EvidenceNodeKindSchema,
  EvidenceNodeLocatorV1Schema,
  EvidenceNodeMetadataV1Schema,
  EvidenceNodeV1Schema,
  EvidenceResolutionAnchorKindSchema,
  EvidenceResolutionV1Schema,
} from "./evidence-graph.js";

export type { ClaudeSourceMetadata } from "./source-metadata.js";
export { ClaudeSourceMetadataSchema } from "./source-metadata.js";
export type {
  ChangeClassificationAggregateLabelV1,
  ChangeClassificationAssignedLabelV1,
  ChangeClassificationDiagnosticCode,
  ChangeClassificationEntryV1,
  ChangeClassificationEvidenceKind,
  ChangeClassificationLabel,
  ChangeClassificationOutcome,
  ChangeClassificationRuleEvidenceV1,
  DeterministicChangeClassificationV1,
} from "./change-classification.js";
export {
  CHANGE_CLASSIFICATION_DIAGNOSTIC_CODES,
  CHANGE_CLASSIFICATION_EVIDENCE_KINDS,
  CHANGE_CLASSIFICATION_LABELS,
  CHANGE_CLASSIFICATION_MAX_ARTIFACT_BYTES,
  CHANGE_CLASSIFICATION_MAX_ENTRIES,
  CHANGE_CLASSIFICATION_OUTCOMES,
  CHANGE_CLASSIFICATION_RULE_SET_VERSION,
  CHANGE_CLASSIFICATION_SCHEMA_VERSION,
  CHANGE_CLASSIFICATION_TAXONOMY_VERSION,
  CHANGE_CLASSIFIER_VERSION,
  ChangeClassificationAggregateLabelV1Schema,
  ChangeClassificationAssignedLabelV1Schema,
  ChangeClassificationDiagnosticCodeSchema,
  ChangeClassificationEntryV1Schema,
  ChangeClassificationEvidenceKindSchema,
  ChangeClassificationLabelSchema,
  ChangeClassificationOutcomeSchema,
  ChangeClassificationRuleEvidenceV1Schema,
  DeterministicChangeClassificationV1Schema,
} from "./change-classification.js";
export type {
  DeterministicVerificationEvidenceV1,
  VerificationCommandObservationV1,
  VerificationEvidenceAggregatesV1,
  VerificationEvidenceDiagnosticCode,
  VerificationEvidenceOutcome,
  VerificationKind,
  VerificationKindAggregateV1,
  VerificationObservedStatus,
  VerificationOutputField,
  VerificationReducedOutputV1,
  VerificationSourceToolOutcome,
  VerificationTestFileChangeV1,
  VerificationToolFamily,
} from "./verification-evidence.js";
export {
  DeterministicVerificationEvidenceV1Schema,
  VERIFICATION_COMMAND_RULE_SET_VERSION,
  VERIFICATION_EVIDENCE_DIAGNOSTIC_CODES,
  VERIFICATION_EVIDENCE_OUTCOMES,
  VERIFICATION_EVIDENCE_SCHEMA_VERSION,
  VERIFICATION_EXTRACTOR_VERSION,
  VERIFICATION_KINDS,
  VERIFICATION_MAX_ARTIFACT_BYTES,
  VERIFICATION_MAX_COMMAND_OBSERVATIONS,
  VERIFICATION_MAX_OUTPUT_EXCERPT_CODE_POINTS,
  VERIFICATION_MAX_REDUCED_OUTPUTS,
  VERIFICATION_MAX_RUN_EVENTS,
  VERIFICATION_MAX_TEST_FILE_REFERENCES,
  VERIFICATION_OBSERVED_STATUSES,
  VERIFICATION_OUTPUT_FIELDS,
  VERIFICATION_OUTPUT_REDUCTION_POLICY_VERSION,
  VERIFICATION_SOURCE_TOOL_OUTCOMES,
  VERIFICATION_TOOL_FAMILIES,
  VerificationCommandObservationV1Schema,
  VerificationEvidenceAggregatesV1Schema,
  VerificationEvidenceDiagnosticCodeSchema,
  VerificationEvidenceOutcomeSchema,
  VerificationKindAggregateV1Schema,
  VerificationKindSchema,
  VerificationObservedStatusSchema,
  VerificationOutputFieldSchema,
  VerificationReducedOutputV1Schema,
  VerificationSourceToolOutcomeSchema,
  VerificationTestFileChangeV1Schema,
  VerificationToolFamilySchema,
} from "./verification-evidence.js";

export type {
  CandidateChangeInteractionV1,
  CandidateCheckInteractionV1,
  CandidateDecisionInteractionV1,
  CandidateMomentBatchV1,
  CandidateMomentChoiceId,
  CandidateMomentChoiceV1,
  CandidateMomentImportance,
  CandidateMomentType,
  CandidateMomentV1,
  CandidateRiskInteractionV1,
} from "./candidate-moment.js";
export {
  CANDIDATE_DECISION_OPTIONS,
  CANDIDATE_MOMENT_CHOICE_LABEL_MAX_BYTES,
  CANDIDATE_MOMENT_CHOICE_LABEL_MAX_CODE_POINTS,
  CANDIDATE_MOMENT_CLAIM_MAX_BYTES,
  CANDIDATE_MOMENT_CLAIM_MAX_CODE_POINTS,
  CANDIDATE_MOMENT_IMPORTANCE_LEVELS,
  CANDIDATE_MOMENT_INTERACTION_TEXT_MAX_BYTES,
  CANDIDATE_MOMENT_INTERACTION_TEXT_MAX_CODE_POINTS,
  CANDIDATE_MOMENT_MAX_BATCH_BYTES,
  CANDIDATE_MOMENT_MAX_BATCH_CANDIDATES,
  CANDIDATE_MOMENT_MAX_EVIDENCE_IDS,
  CANDIDATE_MOMENT_SCHEMA_VERSION,
  CANDIDATE_MOMENT_TITLE_MAX_BYTES,
  CANDIDATE_MOMENT_TITLE_MAX_CODE_POINTS,
  CANDIDATE_MOMENT_TYPES,
  CANDIDATE_RISK_OPTIONS,
  CandidateChangeInteractionV1Schema,
  CandidateCheckInteractionV1Schema,
  CandidateDecisionInteractionV1Schema,
  CandidateMomentBatchV1Schema,
  CandidateMomentChoiceIdSchema,
  CandidateMomentChoiceLabelSchema,
  CandidateMomentChoiceV1Schema,
  CandidateMomentClaimSchema,
  CandidateMomentImportanceSchema,
  CandidateMomentInteractionTextSchema,
  CandidateMomentTitleSchema,
  CandidateMomentTypeSchema,
  CandidateMomentV1Schema,
  CandidateRiskInteractionV1Schema,
  ChangeCandidateMomentV1Schema,
  CheckCandidateMomentV1Schema,
  DecisionCandidateMomentV1Schema,
  RiskCandidateMomentV1Schema,
  parseCandidateMomentBatchV1,
  parseCandidateMomentV1,
} from "./candidate-moment.js";
