import {
  SEMANTIC_ANALYSIS_INPUT_BUILDER_VERSION,
  SEMANTIC_ANALYSIS_MAX_ARTIFACT_BYTES,
  SEMANTIC_ANALYSIS_MAX_BATCH,
  SEMANTIC_ANALYSIS_MAX_RELATIONS,
  SEMANTIC_ANALYSIS_MAX_SUMMARIES,
  SEMANTIC_ANALYSIS_MAX_VERIFICATION_EXCERPTS,
  SEMANTIC_ANALYSIS_REDACTION_POLICY_VERSION,
  SEMANTIC_ANALYSIS_REDUCTION_POLICY_VERSION,
  SEMANTIC_ANALYSIS_TOKEN_ESTIMATOR_VERSION,
} from "@ownloop/contracts";

export const REDUCED_SEMANTIC_ANALYSIS_INPUT_ROLE = "reduced-semantic-analysis-input-v1" as const;
export const REDUCED_SEMANTIC_ANALYSIS_INPUT_KIND = "reduced-semantic-analysis-input-v1" as const;
export const REDUCED_SEMANTIC_ANALYSIS_INPUT_MEDIA_TYPE =
  "application/vnd.ownloop.semantic-analysis-input+json" as const;
export const REDUCED_SEMANTIC_ANALYSIS_INPUT_SENSITIVITY = "sensitive" as const;

export {
  SEMANTIC_ANALYSIS_INPUT_BUILDER_VERSION,
  SEMANTIC_ANALYSIS_MAX_ARTIFACT_BYTES,
  SEMANTIC_ANALYSIS_MAX_BATCH,
  SEMANTIC_ANALYSIS_MAX_RELATIONS,
  SEMANTIC_ANALYSIS_MAX_SUMMARIES,
  SEMANTIC_ANALYSIS_MAX_VERIFICATION_EXCERPTS,
  SEMANTIC_ANALYSIS_REDACTION_POLICY_VERSION,
  SEMANTIC_ANALYSIS_REDUCTION_POLICY_VERSION,
  SEMANTIC_ANALYSIS_TOKEN_ESTIMATOR_VERSION,
};
